In [ ]:
example = {
        "pipe_inner_radius": 0.11,
        "annular_radius": 0.13,
        "rock_radius": 0.14,
        "base_depth": 3600,
        "top_depth": 3200,
        "pipe_wt": 0.02,
        "fluid_wt": 0.01,
        "rock_wt": 14.87
    }

print(type(example))

<class 'dict'>


In [31]:
layers_depths = [3300, 3400, 3500]

data = {
    "ROCK": {"inner_radius": example["rock_radius"],
                "top_depth": example["top_depth"],
                "base_depth": example["base_depth"],
                "thickness": example["rock_wt"],
                "layer_depths": layers_depths
                },

    "FLUID": {"inner_radius": example["annular_radius"],
                "top_depth": example["top_depth"],
                "base_depth": example["base_depth"],
                "thickness": example["fluid_wt"],
                "layer_depths": layers_depths
                },
    "PIPE": {"inner_radius": example["pipe_inner_radius"],
                "top_depth": example["top_depth"],
                "base_depth": example["base_depth"],
                "thickness": example["pipe_wt"],
                "layer_depths": layers_depths
                },
}

print(type(layers_depths))
print(type(data))
print(data.get('ROCK').get('top_depth'))

<class 'list'>
<class 'dict'>
3200


In [21]:
import numpy as np 

a = np.array([[1, 1, 1],[1,2,3],[1,4,2]])
b = np.array([[1,2,3]])

c = np.dot(b,a)

d = np.transpose(c)

print(a)
print(np.shape(a))
print(b)
print(np.shape(b))
print(c)
print(np.shape(c))

print(d)
print(np.shape(d))

[[1 1 1]
 [1 2 3]
 [1 4 2]]
(3, 3)
[[1 2 3]]
(1, 3)
[[ 6 17 13]]
(1, 3)
[[ 6]
 [17]
 [13]]
(3, 1)


In [ ]:
import json 
# import os

# Defining the file paths

json_file_path = r'C:\Users\hidalgo\Documents\GitHub\Abaqus_WELL_\wellClosure_axi.json'
target_script_path = r'C:\Users\hidalgo\Documents\GitHub\Abaqus_WELL_\TestMain.py'

# Reading the paramater from the JSON file

try:
    with open(json_file_path, 'r') as f:
        config_data = json.load(f)

    # --- Navigate through the nested structure to get the value ---
    seawater_depth_json = config_data['ThermalGradient']['seawater'][0]['Depth']

    # Print the result
    print(f"The temperature is: {seawater_depth_json}")
    print(config_data.keys())
    print()


except FileNotFoundError:
    print(f"Error: The file {json_file_path} was not found.")
    exit()  
except json.JSONDecodeError:
    print(f"Error: The file {json_file_path} is not a valid JSON file.")
    exit()

The temperature is: 2000.0
dict_keys(['AnalysisData', 'ThermalGradient', 'Tubulars', 'Lithology', 'InSituStresses', 'Rocks', 'Cements', 'SteelGrades', 'Phases', 'Events', 'Fluids'])
